### ISSUE TITLE
tab is closed when github notifications are closed

### ISSUE THREAD

**Issue by paulrouget** [sindresorhus/notifier-for-github-chrome#102]
Step to reproduce:
- open a tab 1: https://github.com/notifications
- open a tab 2: http://reddit.com
- click on notifier button
- tab 1 is selected
- press Cmd-W (or Ctrl-W)
- tab 1 and tab 2 are closed

**Comment by jacobbearden** [comment]
I am unable to reproduce this, could someone else on a mac see if they can? (I'm not on one)

**Comment by gcochard** [comment]
I can't reproduce this either, and I'm on a mac.

@paulrouget is it reliably reproducible? Try disabling other extensions (turn only this one on in incognito mode to disable the others).

**Comment by paulrouget** [comment]
Sorry - my initial assumption was wrong. I've updated the Step To Reproduce.

**Comment by jacobbearden** [comment]
I was able to reproduce it, will look into the cause.
