### ISSUE TITLE
Extension started showing "und..."

### ISSUE THREAD

**Issue by johanneswuerbach** [sindresorhus/notifier-for-github-chrome#109]
![](https://cloud.githubusercontent.com/assets/864578/20981610/b8389eac-bcb5-11e6-8189-6f766d590523.png)

Recently the extension started showing `und...` without new notifications.

Chrome: 55.0.2883.75
Notifier for GitHub: 2.5.1

**Comment by YurySolovyov** [comment]
can you take a look into network panel to see what the API response was?

**Comment by johanneswuerbach** [comment]
I received a `403 (Forbidden)`, which makes sense as I was just rate-limited by GitHub 🤕
