### ISSUE TITLE
Package is invalid.

### ISSUE THREAD

**Issue by rahulkapoor90** [sindresorhus/notifier-for-github-chrome#111]
version 3.0.0 getting an error "package is invalid, could not load background script.
![chrome_2016-12-13_22-52-41](https://cloud.githubusercontent.com/assets/11207756/21151018/fad349a8-c186-11e6-968b-3ac0f0e92b3f.png)

**Comment by YurySolovyov** [comment]
Did you got it via chrome updates, or just cloned the repo?

**Comment by jacobbearden** [comment]
If you cloned the repository you need to run `webpack`

**Comment by rahulkapoor90** [comment]
@YurySolovyov @jacobbearden i got this when i tried to install it using chrome webstore.

**Comment by krystincodes** [comment]
I am getting the same error when installing through the chrome web store.

**Comment by allen-cook** [comment]
Same here

**Comment by YurySolovyov** [comment]
/here Can you try again? I released 3.0.1

**Comment by allen-cook** [comment]
Install works now for me

**Comment by rahulkapoor90** [comment]
@YurySolovyov  it works now thanks!
