### ISSUE TITLE
Can't worked sometimes.

### ISSUE THREAD

**Issue by jp1017** [sindresorhus/notifier-for-github-chrome#116]
Just like this:

![gitnoti](https://cloud.githubusercontent.com/assets/7868514/23291126/f16a4496-fa90-11e6-866e-40f23f988e87.png)

**Comment by sedubois** [comment]
I have the same issue, almost daily, which make it almost unusable. The only way to clear the error is to disable/enable the extension.

**Comment by YurySolovyov** [comment]
If you can consistently reproduce, can you provide more info and possibly a concrete steps to reproduce the issue?

**Comment by sedubois** [comment]
Unfortunately the issue is frequent, but I don't yet know how to trigger it. Will post back any findings.

**Comment by jansokoly** [comment]
Disconnect from the wifi, wait for the icon to become red, connect to the internet again. The icon will stay in this state until you click it.

**Comment by sedubois** [comment]
Yes I have that issue too. But regularly, even clicking on the icon doesn't refresh its state. So it looks like there are 2 bugs, one which is probably easy to fix (refresh display immediately when connectivity is regained), and maybe another more subtle one.

**Comment by YurySolovyov** [comment]
I would really appreciate you guys taking a look at https://github.com/sindresorhus/notifier-for-github-chrome/pull/120 and reporting if it helps or not.

Make sure to run
```
npm run build
```
to compile the extension

**Comment by YurySolovyov** [comment]
Should  be fixed in 3.0.3, feel free to reopen if this still happens

**Comment by jp1017** [comment]
@YurySolovyov 3.0.3 works well，Great job, Thanks. :smile:
