### ISSUE TITLE
Notification count does not decrease after visiting page

### ISSUE THREAD

**Issue by sedubois** [sindresorhus/notifier-for-github-chrome#121]
The new version of GitHub notifier improves things regarding handling of disconnections thanks to https://github.com/sindresorhus/notifier-for-github-chrome/pull/120 (thanks!), however now the notification count does not seem to decrease after I've opened an issue. I need to click a second time on the button, for it to clear the count.

**Comment by sedubois** [comment]
Actually, sometimes even clicking the button a second time does not fix the issue. One needs to way maybe 30 seconds for it to update its display.

**Comment by gcochard** [comment]
This is intentional and due to the extension respecting the github api rate limit.
