### ISSUE TITLE
"The extension may have been corrupted"

### ISSUE THREAD

**Issue by ahmedelgabri** [sindresorhus/notifier-for-github-chrome#122]
I use Chrome canary & I have 2 profiles, on the latest version on the time of writing this issue `Version 59.0.3067.0 (Official Build) canary (64-bit)` the extension is giving me this error in one of the profiles but not the other. No clue why, everything was working perfectly fine 2 days ago.

<img width="769" alt="screen shot 2017-04-11 at 08 23 39" src="https://cloud.githubusercontent.com/assets/63876/24895474/e0f9ddaa-1e90-11e7-90f1-de21e702ff01.png">

Things I tried:

- Clicking repair doesn't help.
- Reinstalling the extension didn't help.
- I also tried some other solutions like visiting the extensions page on chrome which will show an enable link at the top. which made it work for a bit, but once I click options it crashes again & also the icon always looks like this after doing this.

<img width="37" alt="screen shot 2017-04-11 at 08 32 05" src="https://cloud.githubusercontent.com/assets/63876/24895568/7ed277ee-1e91-11e7-9576-1944c1d2c373.png">

**Comment by dpeukert** [comment]
I have the same issue with `59.0.3071.9 (Official Build) dev (64-bit)` on Windows.

**Comment by yamboy1** [comment]
I had the same problem.Works in 58.0.3029.81 beta though, so moving to the beta version. Does anyone have any idea what is causing this?

**Comment by pauloboc** [comment]
I had the same problem. Works in Versão 59.0.3071.36 beta 64 bits.

**Comment by andrewpong** [comment]
I have the same issue in Chrome `60.0.3088.3 (Official Build) dev (64-bit)` on macOS 10.12.4.

I did the same thing as @ahmedelgabri and got the same result - clicking the icon would open https://github.com/notifications, and clicking Options would crash the extension.

Hopefully [these Extensions Devtool screenshots](http://imgur.com/a/ORllJ) can help - the extension crashed right after the browserAction.onClicked event. As best I can tell it was right when I clicked Options.

**Comment by angrybacon** [comment]
I'm using 60.0.3094.0 (Official Build) canary (64-bit) and it seems to work after I've enabled every Material settings there: chrome://flags/. Try with "Enable Material Design extensions" first.

I was wondering why it would work on my Windows desktop at home but not on macOS at work.

**Comment by vaijab** [comment]
This extension is amazing. I would truly appreciate if someone could fix it.

**Comment by ProLoser** [comment]
I just cloned, `npm install` and `npm run build` and loaded the unpacked extension which seems to behave perfectly fine.

**Comment by RobertGummesson** [comment]
Any update on this? I have the same problem too. Just upgraded to Chrome Canary too.

**Comment by astronouth7303** [comment]
This has cleared up for me.

**Comment by yamboy1** [comment]
I've just updated to the latest unstable release and it works
