### ISSUE TITLE
[QUESTION] Can I have more than one extension dongle for more than one GitHub servers

### ISSUE THREAD

**Issue by vaidsu** [sindresorhus/notifier-for-github-chrome#125]
This is a great add-on, just avoids flooding emails. 

* Can I have more than one API get notified here? I have an internal enterprise GitHub also in the company. 

* If not how do I add one more dongle/button for a different API?

**Comment by YurySolovyov** [comment]
Can't really answer you right away, though if you'll perform your own investigation, that would help a lot.

**Comment by gcochard** [comment]
I recommend signing into two different chrome browser instances (one for work, one for personal) and installing the extension on both.

This necessitates having two different google accounts, but if your company uses google apps you already have this.

**Comment by vaidsu** [comment]
Thanks @YurySolovyov and @gcochard. Let me check further.
