### ISSUE TITLE
What token scopes do you set?

### ISSUE THREAD

**Issue by spences10** [sindresorhus/notifier-for-github-chrome#126]
Just set notification?

![image](https://cloud.githubusercontent.com/assets/234708/25617241/3507b404-2f39-11e7-89dc-7a428629b234.png)

It's not in the README

**Comment by sindresorhus** [comment]
You don't have to check anything. The link from the option panel should have already checked `notifications` for you.

**Comment by spences10** [comment]
So what do you mean by _"Make sure to add a token in the options"_

**Comment by gcochard** [comment]
In the options page, make sure to click the link to add a token. It will pre-fill the required scopes, which you can double-check before creating and using it.

**Comment by gcochard** [comment]
https://github.com/sindresorhus/notifier-for-github-chrome/blob/master/extension/options.html#L34-L35

In the options page it specifies that it needs notification scope for public repos, and both repo and notification scopes for private repos.

**Comment by spences10** [comment]
Ok, I think I've had one too many beers right now, but! The question I asked "what token scopes do you need?" hasn't really been answered with a "yes you need a token with x scope" or "no you don't need to have an access token"

I don't want to be inflammatory, I was perfectly sober when I logged the ticket 👍 

So, do I need to add any sort of GitHub personal access token to the popup that appears after installing the extension?
