### ISSUE TITLE
Background Script in the manifest.json file

### ISSUE THREAD

**Issue by neelanshsahai** [sindresorhus/notifier-for-github-chrome#136]
The script specified in the background section of the manifest.json is incorrect
main.js and manifest.json are on the same directory level so there is no need to use dist/main.js
Also no such directory as dist exists
Allow me to make a PR for this issue.

**Comment by YurySolovyov** [comment]
dist dir is created as part of build process.

**Comment by neelanshsahai** [comment]
okay
I cloned the repo and it was not working because of it...

**Comment by YurySolovyov** [comment]
make sure to run `npm install && npm run build`
