### ISSUE TITLE
Click should always go to notification page...

### ISSUE THREAD

**Issue by smblott-github** [sindresorhus/notifier-for-github-chrome#43]
Please consider reverting (or fixing up) #32 (click when there are no notifications goes to GitHub home page).

Bad use case:

- I get an email notification that there's a new issue/comment.
- Hit `Ctrl-Shift-G` (which I bind to GitHub Notifier).
- But I'm taken to the GitHub page .... 'cause GHN hasn't yet figured out that there's a new notification.

This is a really bad UX.

Possible fixes:

- Wholly revert #32.
- Go to https://github.com/notifications?all=1 if there seems to be no new notifications.
- Add a dynamic check as to whether there are new notifications.

**Comment by sindresorhus** [comment]
@Narno Thoughts?

**Comment by sindresorhus** [comment]
And obligatory XKCD:

![every-change-breaks-someones-workflow](https://cloud.githubusercontent.com/assets/170270/10249995/9fdf2928-6952-11e5-8a3d-c4b265c530bb.png)

**Comment by Narno** [comment]
Hello @smblott-github, thanks for your feedback.

OK, what is happening : GHN fetchs notifications asynchronously from the GH API while respecting the interval allowed between each call.
If you receive an e-mail about a new notification and clicks on the icon (or use a keybord shortcut) between 2 calls, the GHN counter is not yest up-to-date.

About your possible fixes proposals:
> Wholly revert #32.

I love this feature, I can't kill it! :-) (I think @sindresorhus has the last word)

> Go to https://github.com/notifications?all=1 if there seems to be no new notifications.

Not sure it would be usable for most of user, maybe as an option?

> Add a dynamic check as to whether there are new notifications.I like this idea, but I don't know what will be the impacts on performances and risk of API spam.

Maybe the best solution is working on the desktop notification feature? #25 :-)

**Comment by michaelficarra** [comment]
I would revert #32. I do not like this behaviour.

**Comment by sindresorhus** [comment]
Getting the notification count is fast. Why not just fetch the count when the user clicks the button before taking them to GitHub. That way we'll be sure to do the correct thing.

**Comment by smblott-github** [comment]
> Getting the notification count is fast. Why not just fetch the count when the user clicks the button before taking them to GitHub.

That seems better than the status quo.

However, I'd still argue that GHN is not a bookmark for the github home page; it's for notifications.  So [this](https://github.com/notifications?all=1) would be a better alternative target.

(Somebody argued that that might be confusing for users.  No more confusing, I'd say, than dumping them in the home page -- which for at least some users is completely useless.)

**Comment by Narno** [comment]
Another proposal: Do something like https://github.com/Narno/Facebook-Notifier/blob/master/README.md (see the screenshot of the options' page).

**Comment by sindresorhus** [comment]
Ok, let's revert to only going to the notifications page (don't see the point of going to `?all=1`). In hinsight, that makes the most sense. If you want to go to the front page, just use a bookmark.

Sorry @Narno. Not interested in adding an option for this.

**Comment by Narno** [comment]
No problem, I understand.

Now I'm waiting that some guys come here after the revert, to create issues : "wtf, why did you delete this funk*ng smart feature?!" :bowtie:

**Comment by rojepp** [comment]
+1, it was confusing to all of a sudden be taken to GH home page.

**Comment by sindresorhus** [comment]
It has already been decided. Just waiting for someone to do the actual work.

**Comment by rojepp** [comment]
@smblott-github Help me out; How do you bind GitHub notifier to a key?

**Comment by smblott-github** [comment]
@rojepp Go to the extensions page (`chrome://extensions/`), at the bottom on the right, click `keyboard shortcuts`, then follow your nose.
