### ISSUE TITLE
Icon shows maximum 50 unread notifications

### ISSUE THREAD

**Issue by rsalevsky** [sindresorhus/notifier-for-github-chrome#45]
The icon shows maximum 50 unread notifications even when they are more. 

![ghn](https://cloud.githubusercontent.com/assets/4128547/10766968/41eaf112-7cda-11e5-94c3-5d59a5ec9609.png)

I can reproduce this behavior every time, when I remember correct then this is the magic github pagination number.

**Comment by techtonik** [comment]
Most likely a GitHub API limitation. What it could do is fetch and parse https://github.com/notifications HTML directly:
```
 <div class="columns">
        <div class="column one-fourth">
          <ul class="filter-list js-pjax-active" data-pjax>
            <li>
              <a href="/notifications"
                class="filter-item ">
                <span class="count">1583</span>
                Unread
              </a>
            </li>
            <li>
              <a href="/notifications/participating"
                class="filter-item selected">
                <span class="count">121</span>
                Participating
              </a>
            </li>
            <li>
              <a href="/notifications?all=1"
                class="filter-item ">
                All notifications
              </a>
            </li>
          </ul>
```

**Comment by sindresorhus** [comment]
Yes, the GitHub API is paged. We would need to fetch the rest of the pages to show it all. I guess the easiest workaround would be to just show `50+` when it's 50.

**Comment by techtonik** [comment]
That won't help me with 1583 notifications available. Is it possible to read query HTML page instead if the last state was 50+? Or store the value of last page?

**Comment by sindresorhus** [comment]
It actually used to parse the HTML before the API was available. The problem with that is that you have to load all the HTML on each check and it's very fragile for GitHub changing around their HTML.

**Comment by techtonik** [comment]
https://developer.github.com/guides/traversing-with-pagination/ lists that some API calls contain Link header, but that doesn't work for notifications. Have you tried to contact them to query that info?

Otherwise I think it would be ok to maintain code for HTML parsing.

**Comment by sindresorhus** [comment]
> Have you tried to contact them to query that info?

No, I've given up on asking them for stuff. It never happens. I've wasted too much time writing them emails. Feel free though!

> Otherwise I think it would be ok to maintain code for HTML parsing.

PR welcome.

**Comment by SamVerschueren** [comment]
Wouldn't it be better to write a more clever pager?

Just a quick example.

1. Page 1 is loaded and it appears I have more then 50 notifications
2. Page 10 is loaded but it does not exist
3. Page 5 is loaded and returns 50 notifications
4. Page 8 is loaded and returns 10 notifications

Total number of notifications is `7*50 + 10 = 360`

**Comment by sindresorhus** [comment]
@SamVerschueren You're right, that's a better solution. PR welcome for that then.

**Comment by SamVerschueren** [comment]
I'll see if I find the time to do it.

Another thing that can be taken into account to decide where to start is the previous number of notifications. 

1. If my previous notification count is 10.000, start at page `200`
2. Page `200` does not exist, load page `100` which returns 50 notifications
3. Load page `150` (returns 50 notifications)
4. Load page `175` (does not exist)
5. Load page `163` (returns 50 notifications)
6. Load page `169` (returns 5 notifications)

Total number of notifications `168*50 + 5 = 8405`

**Comment by sindresorhus** [comment]
Sounds like a good algorithm.

This might be helpful: https://github.com/Jam3/gh-api-stream

**Comment by techtonik** [comment]
How much steps it will take to find number issue for my `1583`. With doubling the page number it takes just 6 steps. =)
```
1 - 50
2 - 100
4 - 200
8 - 400
16 - 800
32 - 1600 (hit)
```

**Comment by SamVerschueren** [comment]
@techtonik If no previous notification is known, that would be a good fit. If page `32` would not exist, it would check for `(32 + 16) / 2 = 24` and so on...

**Comment by techtonik** [comment]
The only problem is to understand where to inject that code (and keep track on request quota).

**Comment by rojepp** [comment]
I don't think you can do a binary search like this, I see no way to get paged access? You can filter by time, meaning we would have to get all pages sequentially? https://developer.github.com/v3/activity/notifications/#list-your-notifications

**Comment by rojepp** [comment]
I sent a mail with a rudimentary spec suggestion to Github support, let's see what happens.

**Comment by rojepp** [comment]
Got a response from GH

> Sure -- I'll add your suggestion to the API team's wishlist, but I can't make any promises (if I had to guess -- I'd say that this won't be added in the near future).

**Comment by techtonik** [comment]
GH added pagination link headers for Notifications API.
