### ISSUE TITLE
Reuse existing notification tab

### ISSUE THREAD

**Issue by rojepp** [sindresorhus/notifier-for-github-chrome#50]
Great extension, thanks!

I'd like it if a click on the badge takes me to an existing notification tab and reloads it. I always have lots of notification tabs open after a while.

**Comment by sindresorhus** [comment]
Good idea. PR welcome :)

**Comment by corvannoorloos** [comment]
It took a little to figure what happened.
And to get used to, as the notifications tab was always last. (plus I often used it simply to open an additional GitHub page)

But, it has been good thus far. Thanks!

**Comment by corvannoorloos** [comment]
Really paying attention to this, it doesn't always use the existing notifications tab or opens a new tab if not already available. Sometimes a different existing tab is being used (non-GitHub).

It has something to do with already opened GitHub tabs, but still unsure when this exactly happens.

**Comment by sindresorhus** [comment]
@corvannoorloos Open an issue ;)

**Comment by corvannoorloos** [comment]
@sindresorhus I was hoping to come up with a better explanation by now.
