### ISSUE TITLE
Extension always opens in first tab

### ISSUE THREAD

**Issue by edwinksl** [sindresorhus/notifier-for-github-chrome#56]
I am using Chrome for Linux on the dev channel (Version 49.0.2623.13 dev (64-bit)) and the extension now always opens in the first tab.

**Comment by raysegantii** [comment]
Duplicate of https://github.com/sindresorhus/notifier-for-github-chrome/issues/55#issuecomment-173868937 ?

**Comment by edwinksl** [comment]
Looks like this has been fixed by recent updates to Chrome on the dev channel.
