### ISSUE TITLE
Notifications for Participating URL no longer valid

### ISSUE THREAD

**Issue by gauthamchandra** [sindresorhus/notifier-for-github-chrome#58]
Github seems to have changed the way they conceptualize notifications for the repositories you are participating in and they have reflected this in the URL structure.

URL for repositories that you are participating in have changed from: 

> https://github.com/someuser/somerepo/notifications/participating

to just:

> https://github.com/notifications/participating

So when you have the participating count option enabled in options like below:

![image](https://cloud.githubusercontent.com/assets/5430280/12925234/508ed848-cf2b-11e5-9c2a-91bd6cba4ae8.png)

When you click on the extension to go to Github, it leads to a 404.

The code needs to be changed to reflect this new URL.

**Comment by gcochard** [comment]
It seems like you're doing it wrong. I just checked and my extension opens the tab to `https://github.com/notifications/participating` when I have participating checked.

Double-check your root URL settings, as that is where it builds the notification URL from.

**Comment by gauthamchandra** [comment]
@gcochard Damn....I did have that misconfigured. Was messing with something locally and didn't see it. Ugh....My bad!
