### ISSUE TITLE
Wrong tab choice

### ISSUE THREAD

**Issue by LeoColomb** [sindresorhus/notifier-for-github-chrome#60]
Hey!

I got a little issue since few days with Notifier for GitHub on Chrome: when I click on the extension button, my Feedly tab ![image](https://cloud.githubusercontent.com/assets/846943/13530352/3a673f20-e221-11e5-9f08-2b9933698409.png) is focused and moved to GitHub notification, instead of a new fresh tab.

![image](https://cloud.githubusercontent.com/assets/846943/13530039/9b3e1b7c-e21f-11e5-99df-451fc26830ae.png)

Tested:
* No other extension
* Chrome restarted
* Feedly tab refresh
* Feddly tab closed
    * Then the Trello tab ![image](https://cloud.githubusercontent.com/assets/846943/13530332/2483753e-e221-11e5-8337-b73f9b98a13c.png), in fact the second tab, suffer the bug
* Starting with Feedly tab focused
    * Then the Trello tab ![image](https://cloud.githubusercontent.com/assets/846943/13530332/2483753e-e221-11e5-8337-b73f9b98a13c.png), in fact the next tab, suffer the bug
* GitHub Notifications page opened in a new tab
    * Here everything is OK.

Do you have any idea of why? Thanks!

Chrome 49.0.2623.75 m (64-bit)

**Comment by sindresorhus** [comment]
// @rojepp

**Comment by LeoColomb** [comment]
Seriously, I don't understand: all pined tab are selected in the function. Chrome bug or what?

![image](https://cloud.githubusercontent.com/assets/846943/13534637/6eafa974-e236-11e5-8641-ad5ff6c247e5.png)

**Comment by michaelficarra** [comment]
Has to be a chrome bug.

**Comment by LeoColomb** [comment]
@sindresorhus @rojepp 
Are you sure full `tabs` permission is not require for this query?
https://github.com/sindresorhus/notifier-for-github-chrome/blob/222be9923f53121edcb3f123d9249130a4eada9c/extension/manifest.json#L13
https://developer.chrome.com/extensions/activeTab#what-activeTab-allows

**Comment by rojepp** [comment]
@LeoColomb I would think so too from reading that, but if that were true, the behavior should be more deterministic? I still haven't seen this issue myself.. :/

**Comment by LeoColomb** [comment]
I agree.

**Comment by rojepp** [comment]
OTOH, read the first few paragraphs here: https://developer.chrome.com/extensions/tabs

>
You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file. However, if you require access to the url, title, or favIconUrl properties of tabs.Tab, you must declare the "tabs" permission

tabs.query certainly accesses the url, even if we don't use it directly.

**Comment by mainiak** [comment]
Hi.

This is happening for me as well. In my case it's first *pinned* tab in a browser.

What do you need from me to give some more steps to reproduce - @rojepp / @sindresorhus ?

btw. I don't think this extension needs `activeTab` nor `tabs` if you just open new tab based on `browserAction` AFAIK

**Comment by LeoColomb** [comment]
> And it definitely started after Chrome upgrade.

Oh, good catch, I think your right.

> btw. I don't think this extension needs activeTab nor tabs if you just open new tab based on browserAction AFAIK

Not really, because it check other tab if notif page is already opened.

**Comment by sindresorhus** [comment]
Does https://github.com/sindresorhus/notifier-for-github-chrome/commit/0bfd865ecce5bad05ae789f9442ece46fb2e6699 fix it? If not, I'm just going to revert https://github.com/sindresorhus/notifier-for-github-chrome/commit/02f970804c5b9431d8d022bee72aaa5059ba348a. I don't have time to deal with this.

**Comment by SEAPUNK** [comment]
No, I don't think so. I just now loaded the extension at HEAD, but it's still selecting the wrong tab.

However, I added the "tabs" permission to the extension, and now it's selecting the correct tab every time -- I really think it's the `tabs` permission that was "fixed" with the Chrome update.

**Comment by mainiak** [comment]
@sindresorhus - 

Please, keep 0bfd865 Wasn't `selected` deprecated in favour of `highlighted`
Also, I think you should add `tabs`

**Comment by sindresorhus** [comment]
> Please, keep 0bfd865 - Wasn't selected deprecated in favour of highlighted ?

Read my comment again. That's not what I was suggesting.

-

If it's enough to add the `tabs` permission, I guess I could do that instead.

**Comment by SEAPUNK** [comment]
Yeah, I believe the tabs permission fixes the problem. It fixed the problem for me (I'm running Chrome `49.0.2623.87`).

**Comment by sindresorhus** [comment]
New version published. Should be out within the next hour.

**Comment by SEAPUNK** [comment]
Thank you!

**Comment by adam-thomas** [comment]
Thank you @sindresorhus and @SEAPUNK! :)

**Comment by wysow** [comment]
Yes thanks to all!

**Comment by christophlingg** [comment]
works great, thanks

**Comment by mainiak** [comment]
@sindresorhus - Thank you!
