### ISSUE TITLE
Opera Dev 37/38 extension disabled

### ISSUE THREAD

**Issue by licaon-kter** [sindresorhus/notifier-for-github-chrome#62]
Started around when Opera Developer 37 was launched, only seen it in Win 8.1, 64 bit. 
Can't repro in Linux.
Teste both, extension from the Opera store or loaded from a folder.

After a while the extension becomes `deactivated` so I need to go in Extensions and activate it back.
It might be triggered when a new notification appears.

**Comment by sindresorhus** [comment]
No idea. I don't use Opera. I just published it in the Opera extension gallery after @mathiasbynens trolled me about it. I don't have time to debug Opera issues.

**Comment by licaon-kter** [comment]
I'll try to downgrade both Opera and the extension, maybe something stands out.

**Comment by YuriSolovyov** [comment]
@licaon-kter 
I tried installing latest version on windows 10 and Opera 37 and it seems to work fine, can you take a look at ext page (chrome://extensions) and check if it is reporting any errors?

**Comment by licaon-kter** [comment]
It will not happen right away, it even takes 1 hour (I'm using a token, not sure if it matters).

Nothing reported there, just that, compared to my manually disabled extensions, this one has a `reload` button.

Where else are these logged in Windows?

**Comment by licaon-kter** [comment]
In the mean time, can you update the Opera version on their site? It's still at 2.2.2.

**Comment by licaon-kter** [comment]
Chrome version 2.3.2 still gets disabled. ;(

**Comment by licaon-kter** [comment]
Opera 38, straight from GitHub 2.4.0, loaded unpacked, still disappears.
Notifications work though. :)

**Comment by jansokoly** [comment]
After using 2.4.0 with latest stable Opera 37, I don't experience any issue listed above.
Dev builds of browsers are alpha-quality, so they're probably not a good testing ground.
