### ISSUE TITLE
Plugin requires too many permissions

### ISSUE THREAD

**Issue by bquorning** [sindresorhus/notifier-for-github-chrome#64]
With today’s upgrade, I’m seeing this box in the Chrome toolbar:

<img width="308" alt="screen shot 2016-03-10 at 21 34 30" src="https://cloud.githubusercontent.com/assets/22333/13683647/1c93d5e4-e708-11e5-953a-5fddb0733ac7.png">

> **Notifier for GitHub requires new permissions**
> 
> The newest version of the extension "Notifier for
> GitHub" requires more permissions, so it has been
> disabled.
>
> It can now:
> - Read your browsing history

I don’t see any reason to allow this plugin to read my browsing history.

**Comment by Narno** [comment]
Yes, it is "normal" because the recently added "tabs" permission triggers this warning:
https://developer.chrome.com/extensions/permission_warnings#warnings

**Comment by bquorning** [comment]
Well, that’s a bit unfortunate. That’s not a permission that I wish to give to any plugin :-)

As I read main.js, you’re using the Tabs api to check the current tab is empty and otherwise go to a new tab before visiting the GitHub url.

Would it be possible to enable that URL check *only* if the tabs permission has been given?

**Comment by Narno** [comment]
> Would it be possible to enable that URL check only if the tabs permission has been given?

In this case, if this optional permission is not allowed, a new tab will be systematically created. Right?

**Comment by bquorning** [comment]
> In this case, if this optional permission is not allowed, a new tab will be systematically created. Right?

Correct. I would live with that.

**Comment by Narno** [comment]
Hum, I think it's possible with Chrome "optional permissions": could you create a new "feature request" issue? Thx.

**Comment by Narno** [comment]
@sindresorhus what do you think about this request?

**Comment by radiovisual** [comment]
I am also in favor of this "progressive enhancement", where the permission is optional.

**Comment by akarki15** [comment]
as much as i love this extension, i am no longer using it precisely because of this additional permission request

**Comment by radiovisual** [comment]
:+1:  Thanks!
