### ISSUE TITLE
Explain why optional permission is needed

### ISSUE THREAD

**Issue by techtonik** [sindresorhus/notifier-for-github-chrome#68]
I don't know if it is possible, but it would be nice for extension to explain why it requests additional permission when clicking the button for the first time.

**Comment by Narno** [comment]
Hello, I understand but I think it is a bad adea: extensions or app never explain,  on install,  why they need this or those permission.

From my point of view, the best way to answer your request is having a FAQ on the extension page.

It sound good ?

**Comment by sindresorhus** [comment]
Agreed. Too bad Chrome doesn't let us add it in the permission prompt. Would have been better.

**Comment by techtonik** [comment]
FAQ on store description page may work, but I still think that a clear option will be better.

**Comment by YuriSolovyov** [comment]
Added explanation to readme, will also add some info in #66 for `notifications` permission.
Is there anything else we can do here? Extension page in Chrome store is a separate thing, and I guess only @sindresorhus can edit it.

**Comment by sindresorhus** [comment]
Thanks @YuriSolovyov. I've added it to the store page.
