### ISSUE TITLE
Improve app structure

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/notifier-for-github-chrome#75]
ATM it is just a bunch of functions that call each other.
I think we can do better by at least groupping them into related services (just plain objects, really).
This also might help with adding more tests, thought it is not mutually exclusive.

Any other ideas are welcome.

**Comment by techtonik** [comment]
Without a high level diagram of current app structure it is hard to generate better ideas or modify the extension to fit your own purposes. For me it is interesting to use this extension as a template for other notifiers as well.
