### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/notifier-for-github-chrome#76]
This is kind of obvious, but we need more of those. Might be related to #75.
I wonder though if we need to somehow stub GitHub API calls, or we should just intercept that on extension level.

**Comment by YuriSolovyov** [comment]
It would probably be cool to also migrate to Ava

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/notifier-for-github-chrome/issues/90.
