### ISSUE TITLE
Recent versions were not published in Opera Extensions gallery

### ISSUE THREAD

**Issue by jansokoly** [sindresorhus/notifier-for-github-chrome#77]
Last 3 versions were not published in [Opera Extensions gallery](https://addons.opera.com/en/extensions/details/github-notifier). Version 2.2.2 being the last which got published.
If there's something I can help with, let me know. But it's probably just about having credentials for the account and uploading a new package via the site.

**Comment by licaon-kter** [comment]
There is also this: https://github.com/sindresorhus/notifier-for-github-chrome/issues/62

**Comment by jansokoly** [comment]
@sindresorhus can you pass me the credentials to Opera Extensions gallery so I can update the entry to the most recent release?

**Comment by sindresorhus** [comment]
@jansokoly I don't want to share my credentials, but share/email me you Opera addons username and I'll request the extension transferred to you ;)

**Comment by jansokoly** [comment]
@sindresorhus yes, that's better. I've sent it to your gmail. Thanks.

**Comment by sindresorhus** [comment]
I never heard back from the Opera people...

**Comment by jansokoly** [comment]
In June, I pointed you to http://forums.opera.com/discussion/comment/15243581#Comment_15243581. You didn't write the request on extension wall as they suggested.
