### ISSUE TITLE
Desktop notifications showed for non-participating issues too.

### ISSUE THREAD

**Issue by devkhan** [sindresorhus/notifier-for-github-chrome#78]
I get desktop notifications for the issues/PRs in which I'm not participating, even when I have "Only show unread count for issues I'm participating in" enabled.

On the other hand, the extension icon doesn't show the count for non-participating issues/PRs.

**Comment by zubin** [comment]
I'm not sure this is a bug, but personally I'd prefer to only receive desktop notifications for issues I'm participating in. 

Perhaps the "Only show unread count for issues I'm participating in" checkbox could be renamed so it encapsulates behaviour for unread count _and_ desktop notifications (if it's enabled), eg:

> [x] Exclude issues I'm not participating in
> _This affects unread count and desktop notifications (when enabled)._

**Comment by devkhan** [comment]
That's the problem, I receive desktop notifications for non-participating issues even when "Only show unread count for issues I'm participating in" is checked.

Maybe the checkbox doesn't alter the behaviour of the notifications.

**Comment by zubin** [comment]
Understood, I agree with you. But the checkbox text doesn't mention desktop notifications so (IMO) there's no expectation that it necessarily should behave that way.

**Comment by devkhan** [comment]
Agree. So that makes it a feature request instead of a bug.
