### ISSUE TITLE
Use GitHub.js ?

### ISSUE THREAD

**Issue by YuriSolovyov** [sindresorhus/notifier-for-github-chrome#79]
[GitHub.js](https://github.com/michael/github) seems like a great alternative for our custom request handling

**Comment by sindresorhus** [comment]
Why? Is there anything we need that would be a lot simpler with it?

**Comment by YuriSolovyov** [comment]
Not a lot, but I wish it was more modular, so we could only use stuff we need, and after looking at it more,  it looks like it uses too many deps, that provide what we have here for free.
