### ISSUE TITLE
Notification count not updating

### ISSUE THREAD

**Issue by acroca** [sindresorhus/notifier-for-github-chrome#81]
Hi all! In the last 2 weeks the extension sometimes doesn't update the notification count until I click on it. And once I click I think it refreshes for a while and stops again.
This has been happening to a colleague in the office too.
Is this happening to anyone else or is just us for some reason?

**Comment by licaon-kter** [comment]
Have it too in Opera Dev.

**Comment by acroca** [comment]
oh, I didn't say, I use the chrome extension.

**Comment by gcochard** [comment]
When this happens, does it not update when you view notifications, expecting the count to go down? If so, it could be a known (to us) issue with the gh API. Do you have desktop notifications turned on?

**Comment by acroca** [comment]
It does update if I click the extension.
I'm not sure about this, but I think it does NOT update if I visit the notifications page without using the extension.
What is the issue with Github API? I have quite some experience with it, but never used their notifications endpoint.

**Comment by gcochard** [comment]
I ran into an issue where theif-modified-since header only acted correctly if new notifications came in, regardless of the unread status of older ones. It was documented in a PR, I will find it.

**Comment by acroca** [comment]
I see. In my case the extension gets stuck at 0 notifications (so no number at all) right after checking all and marking all as read. So basically I don't know when there are new notifications.

**Comment by licaon-kter** [comment]
(extension from the Chrome store since #77 )
In my case it stays at a red "?".
Also, only the Windows version shows this afaics, so not sure if related to #62

**Comment by gcochard** [comment]
As promised, I found the [relevant discussion](https://github.com/sindresorhus/notifier-for-github-chrome/issues/11#issuecomment-98216511) on notification count not updating.

**Comment by jansokoly** [comment]
I experience this as well.
This bug has been introduced in version 2.4.0. It works just fine in version 2.3.2 and below. I've tried running them side by side.
A good way to reproduce this is to turn off internet connection until Notifier shows red "?". Then turn it back on. Notifier (version 2.4.0) never catches up again and you need to click the button to get it work.

**Comment by seriema** [comment]
I took some screenshots for convenience.

Most of the time: <img width="43" alt="screenshot 2016-06-05 11 10 30" src="https://cloud.githubusercontent.com/assets/693684/15804588/7351926e-2b0e-11e6-9c96-575d8333e025.png">
After I click on it: <img width="33" alt="screenshot 2016-06-05 11 14 18" src="https://cloud.githubusercontent.com/assets/693684/15804593/af15b488-2b0e-11e6-8fdb-b646744f4c82.png"> (as expected)

**Comment by GRA0007** [comment]
Yes this happens to me when my laptop resumes from sleep. It looks like it stops checking every minute if the internet drops out.

**Comment by YurySolovyov** [comment]
Does it say "Unknown error" when you hover it?

**Comment by YurySolovyov** [comment]
Anyway, I created a new branch called [`responsiveness`](https://github.com/YurySolovyov/notifier-for-github-chrome/tree/responsiveness), and it would be nice if someone could check it out and report here if it helps.

**Comment by GRA0007** [comment]
@YurySolovyov Yes it does :)

**Comment by YurySolovyov** [comment]
Awesome, I'll make a PR

**Comment by jansokoly** [comment]
Confirmed. It fixes the issue in Opera.

**Comment by YurySolovyov** [comment]
Thanks all.
@sindresorhus can you release an updated version?

**Comment by sindresorhus** [comment]
Done.
