### ISSUE TITLE
Clicking notifications goes to new and empty tab for private repositories

### ISSUE THREAD

**Issue by gholtslander-va** [sindresorhus/notifier-for-github-chrome#82]
If I get a notification for work going on in a private repository, I can click on it but it just opens a new tab with no url.

Doing some debugging on this it looks like the response back to `handleNotificationClicked` is a 404 "Not Found" from the GitHub API, which makes sense since that's what happens if you try to open one of them in your browser as well.

If I go to the token I gave the app and give it the `repo` permission, things work. One wrinkle in this though is that I also had to change the code in handleNotificationClicked from

```js
fetch(url).then(// ...
```
to

```js
window.GitHubNotify.request(url).then(// ...
```

so that it actually used my token for requests. Without this we were also noticing that there were rate-limiting issues with the public auth on our IP address. A co-worker and I were trying out the extension and were hitting these limits before we found that fix.

This is all a long issue description to say: Are any of the maintainers working on this right now? If not, I can put in a pull request in the next day for it as I've made most of the changes locally. I had one other question though: are the users of this extension alright granting "full control of private repositories" for this extension? If so, I could also add it to the link that gets clicked when it asks you to create a token.

Thanks for the time, I know this was long. After making the changes locally this extension now replaces email notifications for me!

**Comment by gcochard** [comment]
Please make a PR if you've got the work done!

I would be wary of allowing "full control of private repositories" on an extension I found in the chrome store, but we could provide a description to the user saying what the added permissions are for.

I'm a little confused why it would 404 when the notification is delivered, but if I see your diff it'll bring some clarity.

**Comment by gholtslander-va** [comment]
It 404s because it's calling `api.github.com` about a private repository, so without permissions GitHub treats those as "not found", not "access forbidden" (403). If I give it my token and enable full repo access it can use my token to see those repos and all is well.

I suppose we could leave it up to people to manually enable that. Not everyone needs it, only if you have private repositories, and I think it could be adequately explained how to turn that on :+1:

**Comment by gcochard** [comment]
Just reviewed the code and I can see where it hits the GH api for the URL for the notification. I was assuming it was opening the notifications page.

Agreed that we can present both token types in a request to the user, with explanations for which to use.

Looking forward to the PR.
