### ISSUE TITLE
Automate publish

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github-chrome#88]
With: https://github.com/DrewML/chrome-webstore-upload-cli

So any contributor here can just git tag to publish a new release.

Example: https://github.com/sindresorhus/refined-github/blob/38cee1b1559f6ef8b66aedb58bb8e6de5deb56b5/package.json#L4

// @DrewML @paulmolluzzo

**Comment by jacobbearden** [comment]
If the needed `CLIENT_ID`, `CLIENT_SECRET`, and `REFRESH_TOKEN` are set on your end of Travis I can handle this real quick.

**Comment by jacobbearden** [comment]
@sindresorhus got those private variables set?

**Comment by sindresorhus** [comment]
Yup, done.

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/notifier-for-github-chrome/commit/1769af918ff2faacc333b302e3a68bcc3a3be52e.
