### ISSUE TITLE
Single click opens wrong URL

### ISSUE THREAD

**Issue by Crayder** [sindresorhus/notifier-for-github-chrome#96]
So when you single click on the icon it should take you to "https://github.com/notifications" but it takes you to "https://github.com/USERNAME/notifications" instead...

i.e. assuming it accepted my stuff, where I put in my account URL ("https://github.com/Crayder") and my access token.

**Comment by Narno** [comment]
Hello,

In Options you should not put the URL to your GitHub account : it must be the root URL to GitHub OR to your GitHub Enterprise.

ie: https://github.com/

**Comment by Crayder** [comment]
Yeah, I figured that out, I thought I had already closed the issue.

By default it is "api.github.com", I left that and it's working.
