### ISSUE TITLE
You were mentioned.

### ISSUE THREAD

**Issue by Crayder** [sindresorhus/notifier-for-github-chrome#97]
All of the desktop notifications from this say that I have been mentioned, though most of the time that is not the case.

**Comment by YurySolovyov** [comment]
See https://github.com/sindresorhus/notifier-for-github-chrome/pull/66#issuecomment-204926725

**Comment by Crayder** [comment]
So it can't be fixed because the GitHub API has a weird way of handling the `reason`...

**Comment by YurySolovyov** [comment]
@Crayder right.

**Comment by Crayder** [comment]
Well thanks for the info, it's just getting a bit annoying.
